baseURL = 'https://tais2024.cc/'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
title = 'TAIS2024'
copyright = "AI Safety æ±äº¬"
theme = 'hugo-bearcub'
#Â sectionPagesMenu = true
googleAnalytics = ''
enableRobotsTXT = true


[authors.blaine-william-rogers]
  default = true
  name = 'Blaine William Rogers'
  email = 'blaine@aisafety.tokyo'
  github = 'paperclipbadger'
  location = 'Tokyo, Japan' 

[languages]
  [languages.en]
    disabled = false
    contentDir = "content.en"
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'ğŸ‡¬ğŸ‡§ English'
    title = 'TAIS2024'
    weight = 0
  
    [languages.en.params]
      madeWith = 'Made with [Bear Cub](https://github.com/clente/hugo-bearcub)'

  [languages.ja]
    disabled = false
    contentDir = "content.ja"
    languageCode = 'ja-JP'
    languageDirection = 'ltr'
    languageName = 'ğŸ‡¯ğŸ‡µ æ—¥æœ¬èª'
    title = 'TAIS2024'
    weight = 1
    
    [languages.ja.params]
      madeWith = '[ç†Šå­](https://github.com/clente/hugo-bearcub)ã§ç¯‰ãã¾ã—ãŸ'